backend:
  name: git-gateway
  branch: master

media_folder: public/img
public_folder: /img

collections:
  - name: "projects"
    label: "Projekti"
    format: "json"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Naslov", name: "siteTitle", widget: "string", required: true }
      - { label: "Podnaslov", name: "siteSubtitle", widget: "string" }
      - {
        label: "Featured Image",
        name: "featureImage",
        widget: "image",
        required: true,
      }
      - { label: "Intro", name: "intro", widget: "markdown" }
      - label: "Projekti"
        name: "projects"
        widget: "list"
        fields:
          - { label: "Naslov", name: "title", widget: "string", required: true }
          - { label: "Podnaslov", name: "subtitle", widget: "string" }
          - { label: "Opis", name: "description", widget: "markdown", required: true }
          - { label: "Slika", name: "image", widget: "image", required: true }
          - label: "Povezave"
            name: "links"
            widget: "list"
            fields:
              - { label: "Naslov", name: "title", widget: "string", required: true }
              - { label: "Povezava", name: "link", widget: "string", required: true }
              - { label: "Notranja povezava", name: "internalLink", widget: "boolean", default: true }
              - { label: "Vrsta gumba", name: "buttonType", widget: "select", options: [ "primary", "secondary", "text" ], default: "primary" }
  - name: "SSSmembers"
    label: "Člani ŠSS"
    format: "json"
    folder: "content/sss"
    create: true
    slug: "{{slug}}"
    fields:
      - name: title
        label: Naslov
        widget: string
      - name: subtitle
        label: Podnaslov
        widget: string
      - name: intro
        label: Intro
        widget: markdown
      - name: leadership
        label: Vodstvo
        widget: list
        fields:
          - name: name
            label: Ime in priimek
            widget: string
          - name: function
            label: Funkcija
            widget: string
          - name: email
            label: Email
            widget: string
          - name: phone
            label: Telefon
            widget: string
          - name: image
            label: Slika
            widget: image
          - name: backgroundImage
            label: Ozadje
            widget: image
      - name: memberDorms
        label: Domovi
        widget: list
        fields:
          - name: name
            label: Naziv doma
            widget: string
          - name: location
            label: Naselje
            widget: string
          - name: noOfStudents
            label: Število prebivalcev
            widget: number
          - name: dormMotto
            label: Moto
            widget: string
            required: false
          - name: dormImage
            label: Slika doma
            widget: image
          - name: presidentName
            label: Predstavnik
            widget: string
          - name: presidentImage
            label: Slika predstavnika
            widget: image
            required: false
          - name: subPresidentName
            label: Namestnik predstavnika
            widget: string
          - name: subPresidentImage
            label: Slika namestnika predstavnika
            widget: image
            required: false
  - name: "SSSdescription"
    label: "ŠSS - kdo smo"
    format: "json"
    folder: "content/sss/description"
    create: true
    slug: "{{slug}}"
    fields:
      - name: title
        label: Naslov
        widget: string
      - name: subtitle
        label: Podnaslov
        widget: string
      - name: cover
        label: Naslovnica
        widget: image
      - name: intro
        label: Intro
        widget: markdown
      - name: paragraphs
        label: Kartice
        widget: list
        fields:
          - name: title
            label: Naslov
            widget: string
          - name: description
            label: Opis
            widget: markdown
          - name: image
            label: Slika
            widget: image

  - name: "SSSpage"
    label: "Študentski svet stanovalcev"
    format: "json"
    folder: "content/sss-pages"
    create: true
    slug: "{{slug}}"
    fields:
      - name: title
        label: Naslov
        widget: string
      - name: subtitle
        label: Podnaslov
        widget: string
      - name: menuButton
        label: "Besedilo gumba"
        widget: string
      - name: link
        label: Povezava
        widget: string
      - name: cover
        label: Naslovnica
        widget: image
      - name: intro
        label: Intro
        widget: markdown
        required: false
      - name: paragraphs
        label: Kartice
        widget: list
        required: false
        fields:
          - name: title
            label: Naslov
            widget: string
          - name: description
            label: Opis
            widget: markdown
          - name: image
            label: Slika
            widget: image
            required: false
